name: "Cloudron Push to App"
description: "Push your code to a Cloudron app using the Cloudron CLI"
branding:
  icon: "upload-cloud"
  color: "blue"
author: "Cloudron UG"
inputs:
  CLOUDRON_URL:
    description: "Cloudron URL (e.g., https://my.demo.cloudron.io)"
    required: true
    type: "secret"
  CLOUDRON_TOKEN:
    description: "Cloudron API Token"
    required: true
    type: "secret"
  CLOUDRON_APP_ID:
    description: "Cloudron App ID to push the code to - this can also be a location slug e.g. lamp or full domain e.g. lamp.demo.cloudron.io"
    required: true
    type: "secret"
  CLOUDRON-CLI-VERSION:
    description: "Version of the Cloudron CLI to use"
    default: "6.0.0"
  CLOUDRON-PUSH-DESTINATION:
    description: "Destination directory to push the code into - defaults to /app/data/ if not specified"
    default: "/app/data/public/"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.CLOUDRON-CLI-VERSION }}"
  env:
    CLOUDRON_TOKEN: "${{ inputs.CLOUDRON_URL }}"
    CLOUDRON_APP_ID: "${{ inputs.CLOUDRON_APP_ID }}"
    CLOUDRON_URL: "${{ inputs.CLOUDRON_TOKEN }}"
    CLOUDRON_PUSH_DESTINATION: "${{ inputs.CLOUDRON-PUSH-DESTINATION }}"
