name: "Cloudron Push to App"
description: "Push your code to a Cloudron app using the Cloudron CLI"
branding:
  icon: "upload-cloud"
  color: "blue"
author: "Cloudron UG"
inputs:
  CLOUDRON_URL:
    description: "Cloudron URL (e.g., https://my.demo.cloudron.io)"
    required: true
    type: "secret"
  CLOUDRON_TOKEN:
    description: "Cloudron API Token"
    required: true
    type: "secret"
  CLOUDRON_APP_ID:
    description: "Cloudron App ID to push the code to - this can also be a location slug e.g. lamp or full domain e.g. lamp.demo.cloudron.io"
    required: true
    type: "secret"
  CLOUDRON_CLI_VERSION:
    description: "Version of the Cloudron CLI to use"
    default: "6.0.0"
  CLOUDRON_PUSH_DESTINATION:
    description: "Destination directory to push the code into - defaults to /app/data/public if not specified"
    default: "/app/data/public"
  CLOUDRON_CREATE_APP_BACKUP:
    description: "Whether to create a backup of the app before pushing new code"
    required: false
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.CLOUDRON-CLI-VERSION }}"
  env:
    CLOUDRON_TOKEN: "${{ inputs.CLOUDRON_URL }}"
    CLOUDRON_APP_ID: "${{ inputs.CLOUDRON_APP_ID }}"
    CLOUDRON_URL: "${{ inputs.CLOUDRON_TOKEN }}"
    CLOUDRON_PUSH_DESTINATION: "${{ inputs.CLOUDRON_PUSH_DESTINATION }}"
    CLOUDRON_CREATE_APP_BACKUP: "${{ inputs.CLOUDRON_CREATE_APP_BACKUP }}"
